# GitHub
username:             websiddu
repo:                 cook.websiddu.com
branch:               master

# Jekyll source / destination
source:               .
destination:          _site

inc:
  # Blog Information
  title:        "Siddhartha Gudipati"
  subtitle:     "Random thought about design, technology, beauty, and more..."
  cover_image:  blog-cover.jpg
  logo:         cook.svg

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  websiddu

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false

 # Analytics
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html
    tracking_id: UA-55363605-4

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Puritan:400,700|Roboto+Mono:300,400,500|Mandali'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://0.0.0.0:4000
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
incremental: true
# Exclude the following from the Jekyll build process.
# Note: "vendor" is for Travis CI.
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "gulpfile.babel.js",
          ".sass-cache",
          '.gitmodules',
          'styleguie.websiddu.com',
          "_js",
          "node_modules",
          "package.json"]
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0

# relative_permalinks: true

permalink:     none
paginate_path: 'page:num'
paginate: 15

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!--more-->"

safe:        false
host:        0.0.0.0
port:        4012
baseurl:     /
lsi:         false

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

redcloth:
  hard_breaks: true


gems:
  - jekyll-assets
  - jekyll-archives

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - styleguide.websiddu.com/_assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
